#name
name: Dockerise web application

#when does it run
on:
  push:
    branches: [ "main", "my-other-branch" ] #run only when there is a push on the main branch
  pull_request:
    branches: [ "main" ]  #only when there is a pull  request for the main branch


#what jobs will it be running when it triggers
jobs:
  #which manchine is it going to run it on
  build-run-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check that it runs fine. 
      run: ls 

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_PASSWORD  }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME  }}/toyshop-dockerized:gha

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Create Security Group
      run: | 
        aws ec2 create-security-group --group-name MyGHASecGrp --description "SecurityGroup for github action"
